language: node_js

node_js:
    - '0.10'

before_script:
    - 'npm install -g bower'
    - npm install codecov.io
    - 'bower install'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'

script: npm test

after_success:
    - $(npm bin)/codecov < coverage/lcov.info

notifications:
    email: false
